trustPolicy: no-downgrade

shellEmulator: true
catalogs:
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@eslint/markdown': ^8.0.2
    '@stylistic/eslint-plugin': ^5.10.0
    '@typescript-eslint/eslint-plugin': ^8.61.1
    '@typescript-eslint/parser': ^8.61.1
    '@vitest/eslint-plugin': ^1.6.20
    consola: ^3.4.2
    eslint-config-flat-gitignore: ^2.3.0
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.2.3
    eslint-plugin-de-morgan: ^2.1.2
    eslint-plugin-format: ^2.0.1
    eslint-plugin-import-x: ^4.16.2
    eslint-plugin-jsdoc: ^63.0.6
    eslint-plugin-jsonc: ^3.2.0
    eslint-plugin-n: ^18.1.0
    eslint-plugin-perfectionist: ^5.9.1
    eslint-plugin-pnpm: ^1.6.1
    eslint-plugin-tailwindcss: ^4.0.2
    eslint-plugin-unicorn: ^68.0.0
    eslint-plugin-unused-imports: ^4.4.1
    eslint-plugin-vue: ^10.9.2
    eslint-plugin-yml: ^3.4.0
    eslint-processor-vue-blocks: ^2.0.0
    jsonc-eslint-parser: ^3.1.0
    prompts: ^2.4.2
    vue-eslint-parser: ^10.4.1
    yaml-eslint-parser: ^2.0.0
  dev:
    '@eslint/config-inspector': ^3.0.4
    '@types/eslint-plugin-tailwindcss': ^3.17.0
    '@types/node': ^26.0.0
    '@types/prompts': ^2.4.9
    eslint-plugin-markdown-preferences: ^0.41.1
    eslint-typegen: ^2.3.1
    execa: ^9.6.1
    globals: ^17.6.0
    lint-staged: ^17.0.7
    local-pkg: ^1.2.1
    simple-git-hooks: ^2.13.1
    tinyglobby: ^0.2.17
    tsdown: ^0.22.3
    tsx: ^4.22.4
    typescript: ~6.0.3
    vitest: ^4.1.9
    vue: ^3.5.38
  peer:
    '@prettier/plugin-xml': ^3.4.2
    '@unocss/eslint-plugin': ^66.7.2
    eslint: ^10.5.0
  inline:
    find-up-simple: ^1.0.1
minimumReleaseAgeExclude:
  - '@types/node@26.0.0'
  - eslint-plugin-tailwindcss@4.0.2
  - eslint-plugin-unicorn@68.0.0
allowBuilds:
  esbuild: false
  simple-git-hooks: false
  unrs-resolver: false
